### ISSUE TITLE
[Bug]: PersonInfo Method not found.

### ISSUE THREAD

**Issue by talontsi07** [tubearchivist/tubearchivist-jf-plugin#13]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
When using the TubeArchivist Jellyfin plugin, an error occurs related to the PersonInfo.set_Type method, resulting in metadata fetching failure for episodes.

## Steps To Reproduce
Install the TubeArchivist Jellyfin plugin.
Configure the plugin with the required settings.
Attempt to fetch metadata for an episode.
Observe the error in the Jellyfin logs.

## Expected behavior
The metadata for episodes should be fetched and processed without errors, and the PersonInfo should be correctly handled according to the Jellyfin API.

### Relevant Jellyfin log output

```shell
[ERR] Error in "TubeArchivist"
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeMetadataProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeMetadataProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### Anything else?

I rebuilt the plugin after changing `Type = Data.Enums.PersonKind.Actor,` to `Type = Data.Enums.PersonKind.Unknown,` in `EpisodeMetadataProvider.cs` and that has seemed to band aid fix it.

Jellyfin: 10.9.2
TubeArchivistMetadata: 1.3.0.0 from repository TubeArchivistMetadata
TubeArchivist: v0.4.7

**Comment by DarkFighterLuke** [comment]
Mmh, I have some doubts.
First, the solution attempt you found is not logically correct :)
Second, the exception is very strange, because it resembles to one that I saw when using the plugin on an old Jellyfin version. Are you 100% sure about your Jellyfin and plugin versions? Please check them from Jellyfin Dashboard UI.

On my side I am not able to reproduce the issue btw :(

**Comment by talontsi07** [comment]
First, the solution attempt you found is not logically correct :): 
That could be  however "Unknown" is an option for "PersonKind".

PersonKind.cs
```
public enum PersonKind
{
    //
    // Summary:
    //     An unknown person kind.
    Unknown,
    //
    // Summary:
    //     A person whose profession is acting on the stage, in films, or on television.
    Actor,
    //
    // Summary:
    //     A person who supervises th actors and other staff in a film, play, or similar
    //     production.
    Director,
    ......
    ```
    
    Second, the exception is very strange, because it resembles to one that I saw when using the plugin on an old Jellyfin version.:
    I checked and included all the version numbers in my post.

**Comment by DarkFighterLuke** [comment]
@Emporea yes, you are right, I will give a look at the supported version in the manifest, but anyway I am not sure that plugins get automatically updated with the whole Jellyfin.

@talontsi07 yes, Unknown is a valid PersonKind, but not the correct one to set :)

**Comment by DarkFighterLuke** [comment]
> @DarkFighterLuke well I am not 100% sure, but all other plugins i had were automatically upgraded aswell, just tubearchivist not.

Nice to know 💯
I will check the manifest and fix it.
Thanks for noticing 🙂

**Comment by Enoril** [comment]
I have exactly encountered this bug. 

After check of this plugin version in Jellyfin, it seems something goes wrong as i was still at the version 1.2.3.0.

My Jellyfin version is up-to-date (10.9.11) et Jellyfin log on startup display the message regarding auto extension update (in 1 sec) but that doesn't seems to be true.

Could it be because we actively select which version we install during the installation process of the plugin ? 
The version 1.2.3 release date is approximately when I've installed TA... We don't have a "latest" version choice anyway. But the timing could match here.

**Comment by DarkFighterLuke** [comment]
@Enoril i spoke with the guys at Jellyfin and it seems that my manifest is totally correct about the version, so nothing we can do here :)
Glad you solved!
